# Generated by Django 4.2.3 on 2023-07-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_post_slug_alter_post_status_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Publish')], default=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Publish')], default=2),
        ),
    ]
