# Generated by Django 4.2.3 on 2023-07-24 05:41

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_image_url_alter_event_status_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='no_of_donations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seat_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university_name',
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hospital_name', models.CharField(blank=True, max_length=25, null=True)),
                ('no_of_donations', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'hospital',
                'verbose_name_plural': 'hospitals',
                'db_table': 'hospital',
            },
            bases=('api.user',),
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('seat_no', models.CharField(blank=True, max_length=25, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('no_of_donations', models.IntegerField(default=0)),
                ('university_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='api.universityname')),
            ],
            options={
                'verbose_name': 'donor',
                'verbose_name_plural': 'donors',
                'db_table': 'donor',
            },
            bases=('api.user',),
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
    ]
