# Generated by Django 4.2.3 on 2023-07-24 06:17

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_hospital_hospital_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='city',
            new_name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='banned',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='banned',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=14),
            preserve_default=False,
        ),
    ]
