# Generated by Django 4.2.3 on 2023-07-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='university',
            field=models.ManyToManyField(to='api.universityname'),
        ),
    ]
