# Generated by Django 4.2.3 on 2023-07-30 12:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_donation_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=api.models.report_path),
        ),
    ]
